# Default values for warp10.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: warp-poke/warp10-distributed-docker
  tag: 1.3.13
  pullPolicy: IfNotPresent


warp10:
  ingress:
    replicas: 1
  store:
    replicas: 1
  directory:
    replicas: 1
  egress:
    replicas: 1